//! Private, pinned Codex wire generation. Never executes Codex or a host.
use schemars08::schema::RootSchema;
use serde_json::Value;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;
use std::process::Command;
use typify::{TypeSpace, TypeSpaceSettings};

pub const VERSION: &str = "0.160.0";
const SOURCE: &str = "contracts/providers/codex/0.160.0";
const OUTPUT: &str = "crates/ariadne-adapter-codex/src/generated/v0_160_0";
const ROOTS: &[(&str, &str)] = &[
    ("initialize_params", "v1/InitializeParams.json"),
    ("initialize_response", "v1/InitializeResponse.json"),
    (
        "thread_loaded_list_params",
        "v2/ThreadLoadedListParams.json",
    ),
    (
        "thread_loaded_list_response",
        "v2/ThreadLoadedListResponse.json",
    ),
    ("thread_read_params", "v2/ThreadReadParams.json"),
    ("thread_read_response", "v2/ThreadReadResponse.json"),
    ("thread_queue_list_params", "v2/ThreadQueueListParams.json"),
    (
        "thread_queue_list_response",
        "v2/ThreadQueueListResponse.json",
    ),
    ("thread_turns_list_params", "v2/ThreadTurnsListParams.json"),
    (
        "thread_turns_list_response",
        "v2/ThreadTurnsListResponse.json",
    ),
];

pub fn arguments(args: &[String]) -> Result<(&str, bool), String> {
    match args
        .iter()
        .map(String::as_str)
        .collect::<Vec<_>>()
        .as_slice()
    {
        ["gen-codex-wire"] => Ok((VERSION, false)),
        ["gen-codex-wire", "--check"] => Ok((VERSION, true)),
        ["gen-codex-wire", "--version", version] => Ok((version, false)),
        ["gen-codex-wire", "--version", version, "--check"]
        | ["gen-codex-wire", "--check", "--version", version] => Ok((version, true)),
        _ => Err("Usage: cargo xtask gen-codex-wire [--version 0.160.0] [--check]".into()),
    }
}

fn inventory(directory: &Path, base: &Path) -> Result<BTreeMap<String, String>, String> {
    let mut files = BTreeMap::new();
    for entry in fs::read_dir(directory).map_err(|error| error.to_string())? {
        let entry = entry.map_err(|error| error.to_string())?;
        let kind = entry.file_type().map_err(|error| error.to_string())?;
        if kind.is_dir() {
            files.extend(inventory(&entry.path(), base)?);
        } else if kind.is_file() {
            let bytes = fs::read(entry.path()).map_err(|error| error.to_string())?;
            files.insert(
                entry
                    .path()
                    .strip_prefix(base)
                    .map_err(|error| error.to_string())?
                    .to_str()
                    .ok_or("Non-UTF-8 schema path")?
                    .to_owned(),
                format!("{:x}", Sha256::digest(bytes)),
            );
        } else {
            return Err(format!(
                "Nonregular provider artifact: {}",
                entry.path().display()
            ));
        }
    }
    Ok(files)
}

fn verify_inventory(root: &Path) -> Result<(), String> {
    let source = root.join(SOURCE);
    let manifest: Value = serde_json::from_slice(
        &fs::read(source.join("manifest.json")).map_err(|error| error.to_string())?,
    )
    .map_err(|error| error.to_string())?;
    if manifest["codex_version"] != VERSION || manifest["generator"]["typify"] != "0.5.0" {
        return Err("Unsupported Codex wire provenance".into());
    }
    for (directory, key) in [("schema", "schema_sha256"), ("fixtures", "fixture_sha256")] {
        let expected: BTreeMap<String, String> =
            serde_json::from_value(manifest[key].clone()).map_err(|error| error.to_string())?;
        if expected != inventory(&source.join(directory), &source.join(directory))? {
            return Err(format!("Codex {directory} SHA-256 inventory mismatch"));
        }
    }
    Ok(())
}

pub fn generate(root: &Path, version: &str, check: bool) -> Result<(), String> {
    if version != VERSION {
        return Err(format!("Unsupported Codex wire version: {version}"));
    }
    verify_inventory(root)?;
    let temporary = tempfile::tempdir().map_err(|error| error.to_string())?;
    let mut modules = String::from("// Generated by cargo xtask gen-codex-wire. Do not edit.\n");
    let mut files = Vec::new();
    for (module, schema) in ROOTS {
        let input = root.join(SOURCE).join("schema").join(schema);
        let schema: RootSchema = serde_json::from_slice(
            &fs::read(&input).map_err(|error| format!("{}: {error}", input.display()))?,
        )
        .map_err(|error| format!("{}: {error}", input.display()))?;
        let mut settings = TypeSpaceSettings::default();
        settings.with_map_type("std::collections::BTreeMap");
        let mut types = TypeSpace::new(&settings);
        types
            .add_root_schema(schema)
            .map_err(|error| format!("{}: {error}", input.display()))?;
        let name = format!("{module}.rs");
        fs::write(temporary.path().join(&name), format!(
            "// Generated by cargo xtask gen-codex-wire; Codex {VERSION}; typify 0.5.0.\n// Source: {schema_path}\n{}\n",
            types.to_stream(), schema_path = input.strip_prefix(root).map_err(|error| error.to_string())?.display(),
        )).map_err(|error| error.to_string())?;
        files.push(name);
        modules.push_str(&format!("pub(crate) mod {module};\n"));
    }
    fs::write(temporary.path().join("mod.rs"), modules).map_err(|error| error.to_string())?;
    files.push("mod.rs".into());
    let formatted = Command::new("rustfmt")
        .args(["--edition", "2021"])
        .args(files.iter().map(|name| temporary.path().join(name)))
        .output()
        .map_err(|error| format!("rustfmt: {error}"))?;
    if !formatted.status.success() {
        return Err(format!(
            "rustfmt failed: {}",
            String::from_utf8_lossy(&formatted.stderr)
        ));
    }
    let destination = root.join(OUTPUT);
    if destination.exists() {
        for entry in fs::read_dir(&destination).map_err(|error| error.to_string())? {
            let entry = entry.map_err(|error| error.to_string())?;
            if !entry
                .file_type()
                .map_err(|error| error.to_string())?
                .is_file()
                || !files.iter().any(|name| entry.file_name() == name.as_str())
            {
                return Err(format!(
                    "Unexpected wire artifact: {}",
                    entry.path().display()
                ));
            }
        }
    }
    for name in files {
        let expected = fs::read(temporary.path().join(&name)).map_err(|error| error.to_string())?;
        let target = destination.join(name);
        if check {
            if fs::read(&target).map_err(|error| format!("{}: {error}", target.display()))?
                != expected
            {
                return Err(format!("Stale generated wire: {}", target.display()));
            }
        } else {
            fs::create_dir_all(&destination).map_err(|error| error.to_string())?;
            fs::write(&target, expected).map_err(|error| error.to_string())?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repository() -> &'static Path {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .parent()
            .unwrap()
    }

    #[test]
    fn committed_wire_matches_verified_schemas() {
        generate(repository(), VERSION, true).unwrap();
    }

    #[test]
    fn version_mismatch_is_rejected_before_io() {
        assert!(generate(Path::new("missing"), "0.160.1", true)
            .unwrap_err()
            .contains("Unsupported"));
    }

    #[test]
    fn command_arguments_accept_only_documented_options() {
        for (args, check) in [
            (vec!["gen-codex-wire"], false),
            (vec!["gen-codex-wire", "--check"], true),
            (vec!["gen-codex-wire", "--version", VERSION], false),
            (
                vec!["gen-codex-wire", "--version", VERSION, "--check"],
                true,
            ),
            (
                vec!["gen-codex-wire", "--check", "--version", VERSION],
                true,
            ),
        ] {
            let args = args.into_iter().map(str::to_owned).collect::<Vec<_>>();
            assert_eq!(arguments(&args).unwrap(), (VERSION, check));
        }
        for args in [
            vec![],
            vec!["gen-codex-wire", "--version"],
            vec!["gen-codex-wire", "--check", "--check"],
            vec!["gen-codex-wire", "--host"],
        ] {
            assert!(arguments(&args.into_iter().map(str::to_owned).collect::<Vec<_>>()).is_err());
        }
    }

    #[test]
    fn generation_round_trip_and_drift_detection() {
        let temporary = tempfile::tempdir().unwrap();
        let source = repository().join(SOURCE);
        fn copy(source: &Path, target: &Path) {
            fs::create_dir_all(target).unwrap();
            for entry in fs::read_dir(source).unwrap() {
                let entry = entry.unwrap();
                if entry.file_type().unwrap().is_dir() {
                    copy(&entry.path(), &target.join(entry.file_name()));
                } else {
                    fs::copy(entry.path(), target.join(entry.file_name())).unwrap();
                }
            }
        }
        copy(&source, &temporary.path().join(SOURCE));
        generate(temporary.path(), VERSION, false).unwrap();
        generate(temporary.path(), VERSION, true).unwrap();
        let wire = temporary.path().join(OUTPUT).join("initialize_params.rs");
        let original = fs::read(&wire).unwrap();
        fs::write(&wire, "// drift\n").unwrap();
        assert!(generate(temporary.path(), VERSION, true)
            .unwrap_err()
            .contains("Stale"));
        assert_eq!(fs::read(&wire).unwrap(), b"// drift\n");
        fs::write(&wire, original).unwrap();
        fs::write(temporary.path().join(OUTPUT).join("obsolete.rs"), "").unwrap();
        assert!(generate(temporary.path(), VERSION, true)
            .unwrap_err()
            .contains("Unexpected"));
        fs::write(
            temporary
                .path()
                .join(SOURCE)
                .join("schema/v1/InitializeParams.json"),
            "{}",
        )
        .unwrap();
        assert!(generate(temporary.path(), VERSION, true)
            .unwrap_err()
            .contains("SHA-256"));
    }
}
