//! CLI/MCP and Tauri schemas derive from the same Rust service contract.
use ariadne_core::*;
use schemars::JsonSchema;
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use ts_rs::TS;

pub const SCHEMAS: &str = "contracts/generated/core";
pub const TYPES: &str = "apps/desktop/src/generated/core";
fn schema<T: JsonSchema>() -> schemars::Schema {
    schemars::generate::SchemaSettings::default()
        .for_serialize()
        .into_generator()
        .into_root_schema_for::<T>()
}
fn add<T: JsonSchema + TS>(
    files: &mut BTreeMap<PathBuf, String>,
    types: &mut BTreeMap<String, String>,
) -> Result<(), String> {
    files.insert(
        Path::new(SCHEMAS).join(format!("{}.schema.json", T::schema_name())),
        serde_json::to_string_pretty(&schema::<T>()).map_err(|error| error.to_string())? + "\n",
    );
    let config = ts_rs::Config::default();
    types.insert(T::ident(&config), format!("export {}", T::decl(&config)));
    Ok(())
}
pub fn artifacts() -> Result<BTreeMap<PathBuf, String>, String> {
    let mut files = BTreeMap::new();
    let mut types = BTreeMap::new();
    macro_rules! register { ($($ty:ty),+ $(,)?) => { $(add::<$ty>(&mut files, &mut types)?;)+ }; }
    register!(
        ApplyRequest,
        EntityRef,
        ExistingRef,
        LocalRef,
        UuidRef,
        ExistingUuidRef,
        Operation,
        ItemAddOperation,
        ItemPatch,
        ResultDraft,
        CoreError,
        CoreErrorCode,
        FieldError,
        ErrorDetails,
        BarrierReason,
        QueryRequest,
        ProjectListRequest,
        SessionListRequest,
        SessionRef,
        ItemRoute,
        SessionChangedHint,
        PresenceChangedHint,
        OpenRoute,
        ReadView,
        SessionReadRequest,
        ItemPageRequest,
        ItemMessagesRequest,
        ItemRoundsRequest,
        RoundPageRequest,
        QueryResult,
        ProjectListResult,
        SessionListResult,
        SessionSnapshot,
        SessionReadResult,
        InputQueueEntry,
        ContinuePreviewRequest,
        ContinuePreview,
        ContinueItemPreview,
        ContinueCopyAction,
        ContinueReadiness,
        ContinueBlockReason,
        PageLimit,
        PreferencesSnapshot,
        GlobalPreferences,
        Theme,
        WindowGeometry,
        SessionPreferences,
        ViewFilters,
        RailView,
        ScrollAnchor,
        OwnerDraft,
        PreferencesPatch,
        PreferencesPatchEntry,
        OwnerCommand,
        ProjectRegisterParams,
        BindingConnectParams,
        BindingStateParams,
        InputSubmitParams,
        InputCancelParams,
        InputResolveParams,
        TopicLifecycleParams,
        SessionLifecycleParams,
        TopicContinueParams,
        MutationReceipt,
        ProjectRegisteredReceipt,
        PreferencesPatchedReceipt,
        ClaimRequest,
        PreparedAttempt,
        EventReceipt,
        SuccessFlag,
        FailureFlag,
        SuccessEnvelope<QueryResult>,
        ApplicationEnvelope<QueryResult>,
        FailureEnvelope,
        QueryEnvelope,
        MutationEnvelope,
        ApplyEnvelope,
        ClaimEnvelope,
        ReportEnvelope,
        AgentApplyToolRequest,
        AgentReadToolRequest,
        AgentMessagesToolRequest,
        AgentRoundsToolRequest,
        OwnerQueryRequest,
        OwnerMutationRequest
    );
    let body = types.values().cloned().collect::<Vec<_>>().join("\n") + "\n";
    let tokens: BTreeSet<_> = body
        .split(|c: char| !c.is_ascii_alphanumeric() && c != '_')
        .collect();
    let domain = crate::domain_models::artifacts()?;
    let models = &domain[Path::new(crate::domain_models::TYPES)
        .join("index.ts")
        .as_path()];
    let names: Vec<_> = models
        .split("export type ")
        .skip(1)
        .filter_map(|part| {
            part.split(|c: char| !c.is_ascii_alphanumeric() && c != '_')
                .next()
        })
        .filter(|name| tokens.contains(name))
        .collect();
    let mut text = String::from("// Generated by cargo xtask gen-contracts. Do not edit.\n");
    for name in [
        "UuidV4",
        "ItemRef",
        "UtcMillis",
        "SchemaVersion",
        "PositiveSafeInteger",
        "NonnegativeSafeInteger",
        "Sha256",
        "RequestRef",
    ] {
        if tokens.contains(name) {
            text.push_str(&format!(
                "import type {{ {name} }} from '../domain/primitives/{name}';\n"
            ));
        }
    }
    text.push_str(&format!(
        "import type {{ {} }} from '../domain/models';\n",
        names.join(", ")
    ));
    text.push_str(&body);
    files.insert(Path::new(TYPES).join("index.ts"), text);
    // Transport manifests contain schema references by name for Tauri/CLI and
    // full canonical input schemas for MCP registration. Contexts are absent.
    let tools = serde_json::json!({"api_version":1,"tools":[
        {"name":"session_read","inputSchema":schema::<AgentReadToolRequest>(),"output_schema":QueryEnvelope::schema_name()},
        {"name":"item_messages","inputSchema":schema::<AgentMessagesToolRequest>(),"output_schema":QueryEnvelope::schema_name()},
        {"name":"item_rounds","inputSchema":schema::<AgentRoundsToolRequest>(),"output_schema":QueryEnvelope::schema_name()},
        {"name":"apply","inputSchema":schema::<AgentApplyToolRequest>(),"output_schema":ApplyEnvelope::schema_name()}
    ]});
    files.insert(
        Path::new(SCHEMAS).join("mcp-tools.json"),
        serde_json::to_string_pretty(&tools).map_err(|error| error.to_string())? + "\n",
    );
    let service = serde_json::json!({"api_version":1,"entrypoints":{
        "query":{"request":"QueryRequest","owner_transport_request":"OwnerQueryRequest","result":QueryEnvelope::schema_name()},
        "execute_owner":{"request":"OwnerCommand","owner_transport_request":"OwnerMutationRequest","result":MutationEnvelope::schema_name()},
        "apply":{"request":"ApplyRequest","result":ApplyEnvelope::schema_name()},
        "claim":{"request":"ClaimRequest","result":ClaimEnvelope::schema_name()},
        "report":{"request":"../adapter/NormalizedEvent","result":ReportEnvelope::schema_name()}
    },"cli_json":"application envelope","tauri_commands":"QueryRequest and OwnerCommand command tags","context":"trusted local entrypoint only"});
    files.insert(
        Path::new(SCHEMAS).join("service.json"),
        serde_json::to_string_pretty(&service).map_err(|error| error.to_string())? + "\n",
    );
    Ok(files)
}
