//! Complete canonical domain contracts; primitive exports remain separate.
use ariadne_domain::models::*;
use schemars::JsonSchema;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use ts_rs::TS;

pub const SCHEMAS: &str = "contracts/generated/domain/models";
pub const TYPES: &str = "apps/desktop/src/generated/domain/models";

fn add<T: JsonSchema + TS>(
    files: &mut BTreeMap<PathBuf, String>,
    declarations: &mut BTreeMap<String, String>,
) -> Result<(), String> {
    let schema = schemars::generate::SchemaSettings::default()
        .for_serialize()
        .into_generator()
        .into_root_schema_for::<T>();
    if files
        .insert(
            Path::new(SCHEMAS).join(format!("{}.schema.json", T::schema_name())),
            serde_json::to_string_pretty(&schema).map_err(|error| error.to_string())? + "\n",
        )
        .is_some()
    {
        return Err(format!("Duplicate model schema name: {}", T::schema_name()));
    }
    let config = ts_rs::Config::default();
    declarations.insert(T::ident(&config), format!("export {}", T::decl(&config)));
    Ok(())
}

pub fn artifacts() -> Result<BTreeMap<PathBuf, String>, String> {
    let mut files = BTreeMap::new();
    let mut declarations = BTreeMap::new();
    macro_rules! register {
        ($($type:ty),+ $(,)?) => { $(add::<$type>(&mut files, &mut declarations)?;)+ };
    }
    register!(
        Project, Session, SessionState, SessionCounters, Topic, Item, ItemType, ItemStatus, AckTarget,
        ItemOwner, ItemOption, ItemLinkTarget, LinkKind, StatusHistoryEntry, Message,
        MessageAuthor, MessageKind, Answer, Round, TopicOrigin, ItemOrigin, MessageOrigin, MessageSourceTarget,
        RoundOrigin, EndpointFingerprint, EndpointRef, AdapterConfig, Capability,
        Capabilities, DeliveryMode, Binding, DispatchState, PauseReason, ConnectionState,
        PresenceObservation, ExecutionState, PresenceSource, Freshness, ProcessIdentity,
        Input, InputKind, InputState, CancelCause, InputTarget, InputPayload, RemovedNotice, RemovedRef,
        RemovalTarget, AgentRemovalSource, AgentRemoval, InputTargetSnapshot,
        InputContext, Attempt, AttemptPurpose, AcceptanceState, TurnState, ResultState,
        HostReceipt, DomainResult, ResultOutcome, AttemptError, ResolutionHistoryEntry,
        ResolutionKind, OwnerResolutionEvidence, OwnerEvidenceSource, Checkpoint,
        ReceiptActorScope, OperationReceipt, SavedReceipt, SavedReceiptData, AllocatedRef,
        MessageIdentity, ContinuationReceipt, SummaryCounts, ItemsByStatus, SentInputCounts,
        Completeness, QueryCursor, QueryView, CursorPosition, ItemSnapshot,
        ItemReadProjection, RoundSnapshot, RoundProjection, ResultProjection, ItemLink,
        ItemMessagesProjection, TimelineContext, ItemRoundsProjection, ProjectSummary,
        ProjectAvailability, SessionSummary, BindingSummary,
        Page<ProjectSummary>, Page<SessionSummary>, Page<Topic>, Page<ItemSnapshot>,
        Page<ItemReadProjection>, Page<Message>, Page<Input>, Page<Answer>,
        Page<StatusHistoryEntry>, Page<RoundProjection>, Page<ResultProjection>, Page<ItemLink>,
        serde_json::Value, UniqueMap<String, serde_json::Value>,
    );
    let mut types = String::from("// Generated by cargo xtask gen-contracts. Do not edit.\n");
    for name in [
        "ItemRef",
        "NonnegativeSafeInteger",
        "PositiveSafeInteger",
        "RequestRef",
        "SchemaVersion",
        "Sha256",
        "UtcMillis",
        "UuidV4",
    ] {
        types.push_str(&format!(
            "import type {{ {name} }} from '../primitives/{name}';\n"
        ));
    }
    for declaration in declarations.values() {
        types.push_str(declaration);
        types.push('\n');
    }
    files.insert(Path::new(TYPES).join("index.ts"), types);
    Ok(files)
}
