use ariadne_domain::models::{
    ItemRef, NonnegativeSafeInteger, PositiveSafeInteger, RequestRef, SchemaVersion, Sha256,
    UtcMillis, UuidV4,
};
use schemars::JsonSchema;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use ts_rs::TS;

const SCHEMAS: &str = "contracts/generated/domain/primitives";
const TYPES: &str = "apps/desktop/src/generated/domain/primitives";

pub fn arguments(args: &[String]) -> Result<bool, String> {
    match args
        .iter()
        .map(String::as_str)
        .collect::<Vec<_>>()
        .as_slice()
    {
        ["gen-contracts"] => Ok(false),
        ["gen-contracts", "--check"] => Ok(true),
        _ => Err("Usage: cargo xtask gen-contracts [--check]".into()),
    }
}

fn add<T: JsonSchema + TS>(files: &mut BTreeMap<PathBuf, String>) -> Result<(), String> {
    let schema = schemars::generate::SchemaSettings::default()
        .for_serialize()
        .into_generator()
        .into_root_schema_for::<T>();
    let name = T::schema_name();
    files.insert(
        Path::new(SCHEMAS).join(format!("{name}.schema.json")),
        serde_json::to_string_pretty(&schema).map_err(|error| error.to_string())? + "\n",
    );
    files.insert(
        Path::new(TYPES).join(format!("{name}.ts")),
        format!(
            "// Generated by cargo xtask gen-contracts. Do not edit.\nexport {}\n",
            T::decl(&ts_rs::Config::default())
        ),
    );
    Ok(())
}

pub fn artifacts() -> Result<BTreeMap<PathBuf, String>, String> {
    let mut files = BTreeMap::new();
    add::<UuidV4>(&mut files)?;
    add::<ItemRef>(&mut files)?;
    add::<UtcMillis>(&mut files)?;
    add::<SchemaVersion>(&mut files)?;
    add::<PositiveSafeInteger>(&mut files)?;
    add::<NonnegativeSafeInteger>(&mut files)?;
    add::<Sha256>(&mut files)?;
    add::<RequestRef>(&mut files)?;
    Ok(files)
}

pub fn generate(root: &Path, check: bool) -> Result<(), String> {
    let files = artifacts()?;
    for directory in [SCHEMAS, TYPES] {
        let target = root.join(directory);
        let mut ancestor = target.as_path();
        while ancestor != root {
            if ancestor.is_symlink() {
                return Err(format!(
                    "Generated path is symlinked: {}",
                    ancestor.display()
                ));
            }
            ancestor = ancestor.parent().ok_or("Invalid output root")?;
        }
        if target.exists() {
            for entry in fs::read_dir(&target).map_err(|error| error.to_string())? {
                let entry = entry.map_err(|error| error.to_string())?;
                if !entry
                    .file_type()
                    .map_err(|error| error.to_string())?
                    .is_file()
                    || !files.contains_key(&Path::new(directory).join(entry.file_name()))
                {
                    return Err(format!(
                        "Unexpected generated artifact: {}",
                        entry.path().display()
                    ));
                }
            }
        }
    }
    for (relative, content) in files {
        let target = root.join(relative);
        if check {
            if fs::read_to_string(&target)
                .map_err(|error| format!("{}: {error}", target.display()))?
                != content
            {
                return Err(format!("Stale generated artifact: {}", target.display()));
            }
        } else {
            fs::create_dir_all(target.parent().ok_or("Missing output directory")?)
                .map_err(|error| error.to_string())?;
            fs::write(&target, content).map_err(|error| error.to_string())?;
        }
    }
    Ok(())
}
