//! Adapter method/event exports reuse canonical domain support declarations.
use ariadne_agent_protocol::*;
use schemars::JsonSchema;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use ts_rs::TS;

pub const SCHEMAS: &str = "contracts/generated/adapter";
pub const TYPES: &str = "apps/desktop/src/generated/adapter";

fn add<T: JsonSchema + TS>(
    files: &mut BTreeMap<PathBuf, String>,
    types: &mut BTreeMap<String, String>,
) -> Result<(), String> {
    let schema = schemars::generate::SchemaSettings::default()
        .for_serialize()
        .into_generator()
        .into_root_schema_for::<T>();
    files.insert(
        Path::new(SCHEMAS).join(format!("{}.schema.json", T::schema_name())),
        serde_json::to_string_pretty(&schema).map_err(|error| error.to_string())? + "\n",
    );
    let config = ts_rs::Config::default();
    types.insert(T::ident(&config), format!("export {}", T::decl(&config)));
    Ok(())
}

pub fn artifacts() -> Result<BTreeMap<PathBuf, String>, String> {
    let mut files = BTreeMap::new();
    let mut types = BTreeMap::new();
    macro_rules! register {
        ($($type:ty),+ $(,)?) => { $(add::<$type>(&mut files, &mut types)?;)+ };
    }
    register!(
        AdapterError,
        AdapterErrorCode,
        ProbeRequest,
        ProbeResult,
        Compatibility,
        Availability,
        ConnectRequest,
        ConnectResult,
        SubmitRequest,
        SubmitOutcome,
        ObserveLimit,
        ObserveRequest,
        ObserveResult,
        ReconcileRequest,
        ReconcileResult,
        AttemptEvidenceRequest,
        AttemptEvidence,
        DisconnectRequest,
        DisconnectResult,
        NormalizedEvent,
        EventPayload,
        OutputPhase,
        OutputOperation,
        TurnFinishedStatus,
        TerminalEventKind
    );
    let mut text = String::from("// Generated by cargo xtask gen-contracts. Do not edit.\n");
    for name in ["Sha256", "UtcMillis", "UuidV4"] {
        text.push_str(&format!(
            "import type {{ {name} }} from '../domain/primitives/{name}';\n"
        ));
    }
    text.push_str("import type { AdapterConfig, Capabilities, Checkpoint, EndpointFingerprint, EndpointRef, HostReceipt, PresenceObservation } from '../domain/models';\n");
    for declaration in types.values() {
        text.push_str(declaration);
        text.push('\n');
    }
    files.insert(Path::new(TYPES).join("index.ts"), text);
    Ok(files)
}
