//! Deterministic adapter instructions from authored shared sources: the core
//! rules (`source.md`), the shared skill guidance (`skill.md`) and the
//! on-demand files (`ON_DEMAND`) that ship beside each skill.
use std::{fs, path::Path};

/// Files loaded only when the core skill points at them, one source each.
const ON_DEMAND: [&str; 7] = [
    "inputs.md",
    "errors.md",
    "reconnect.md",
    "report.md",
    "review.md",
    "checklist.md",
    "follow-up.md",
];

const CLAUDE_DESCRIPTION: &str = "File work in Ariadne as topics and items, not long chat replies; also for [ARIADNE_INPUT:] messages. Needs a connected session: if not, ask the owner to run /ariadne-connect and load nothing else.";
const CODEX_DESCRIPTION: &str = "File work in Ariadne as topics and items, not long chat replies; also for [ARIADNE_INPUT:] messages. Needs a connected thread: if not, ask the owner for the setup instruction and load nothing else.";

/// Keep `only:<agent>` blocks for `agent`; drop the others. Marker lines vanish.
fn select(body: &str, agent: &str) -> Result<String, String> {
    let mut out = String::new();
    let mut block: Option<String> = None;
    for line in body.split_inclusive('\n') {
        let trimmed = line.trim();
        if let Some(name) = trimmed
            .strip_prefix("<!-- only:")
            .and_then(|rest| rest.strip_suffix(" -->"))
        {
            if block.is_some() {
                return Err("Nested skill blocks are not allowed".into());
            }
            block = Some(name.to_owned());
        } else if trimmed == "<!-- /only -->" {
            if block.take().is_none() {
                return Err("Unmatched skill block end".into());
            }
        } else if block.as_deref().is_none_or(|name| name == agent) {
            out.push_str(line);
        }
    }
    if block.is_some() {
        return Err("Unterminated skill block".into());
    }
    Ok(out)
}

/// The skill text without front matter: shared guidance, then the core rules.
fn skill_text(skill_body: &str, rules: &str, agent: &str) -> Result<String, String> {
    let selected = select(skill_body, agent)?;
    Ok(format!(
        "{}\n{rules}",
        selected.replace("{{RULES}}", "the rules below")
    ))
}

fn skill(skill_body: &str, rules: &str, agent: &str) -> Result<String, String> {
    let header = "<!-- Generated by cargo xtask gen-rules from rules/skill.md. Do not edit. -->";
    let description = if agent == "claude" {
        CLAUDE_DESCRIPTION
    } else {
        CODEX_DESCRIPTION
    };
    Ok(format!(
        "---\nname: ariadne\ndescription: {description}\n---\n{header}\n{}",
        skill_text(skill_body, rules, agent)?
    ))
}

fn on_demand(name: &str, body: &str, agent: &str) -> Result<String, String> {
    let header =
        format!("<!-- Generated by cargo xtask gen-rules from rules/{name}. Do not edit. -->");
    Ok(format!("{header}\n{}", select(body, agent)?))
}

fn write_or_check(target: &Path, content: &str, check: bool) -> Result<(), String> {
    if target.is_symlink() {
        return Err(format!("Rule output is symlinked: {}", target.display()));
    }
    if check {
        if fs::read_to_string(target).map_err(|error| format!("{}: {error}", target.display()))?
            != content
        {
            return Err(format!("Stale generated rules: {}", target.display()));
        }
        Ok(())
    } else {
        fs::write(target, content).map_err(|error| format!("{}: {error}", target.display()))
    }
}

fn read_source(path: &Path) -> Result<String, String> {
    if path.is_symlink() {
        return Err("Rule source must be a regular owned repository file".into());
    }
    let body = fs::read_to_string(path).map_err(|error| format!("{}: {error}", path.display()))?;
    if body.trim().is_empty() || body.contains('\0') {
        return Err("Rule source must be nonblank and NUL-free".into());
    }
    Ok(body)
}

pub fn generate(root: &Path, check: bool) -> Result<(), String> {
    let directory = root.join("integrations/rules");
    for path in [root.join("integrations"), directory.clone()] {
        if path.is_symlink() {
            return Err(format!("Rule path is symlinked: {}", path.display()));
        }
    }
    let body = read_source(&directory.join("source.md"))?;
    let skill_body = read_source(&directory.join("skill.md"))?;
    let mut on_demand_bodies = Vec::new();
    for name in ON_DEMAND {
        on_demand_bodies.push((name, read_source(&directory.join(name))?));
    }
    // The rule sheets are the skill text for a host that cannot load the skill.
    for agent in ["claude", "codex"] {
        let content = format!(
            "<!-- Generated by cargo xtask gen-rules from skill.md and source.md. Do not edit. -->\n{}",
            skill_text(&skill_body, &body, agent)?
        );
        write_or_check(&directory.join(format!("{agent}.md")), &content, check)?;
    }
    for (agent, relative) in [
        ("claude", "integrations/claude/plugin/skills/ariadne"),
        ("codex", "integrations/codex/skills/ariadne"),
    ] {
        let target_directory = root.join(relative);
        let mut ancestor = target_directory.as_path();
        while ancestor != root {
            if ancestor.is_symlink() {
                return Err(format!("Skill path is symlinked: {}", ancestor.display()));
            }
            ancestor = ancestor.parent().ok_or("Skill path escapes the root")?;
        }
        if !check {
            fs::create_dir_all(&target_directory)
                .map_err(|error| format!("{}: {error}", target_directory.display()))?;
        }
        write_or_check(
            &target_directory.join("SKILL.md"),
            &skill(&skill_body, &body, agent)?,
            check,
        )?;
        for (name, source) in &on_demand_bodies {
            write_or_check(
                &target_directory.join(name),
                &on_demand(name, source, agent)?,
                check,
            )?;
        }
    }
    Ok(())
}
