//! Deterministic adapter instructions from authored shared sources: the rule
//! sheet (`source.md`) and the shared skill guidance (`skill.md`).
use std::{fs, path::Path};

const CLAUDE_DESCRIPTION: &str = "Use when a message starts with an [ARIADNE_INPUT:<input>:<attempt>] marker (a dispatched Ariadne owner input), or when publishing findings to Ariadne. Publish item replies and finish the claimed input with an explicit result.";
const CODEX_DESCRIPTION: &str = "Use when an input starts with an [ARIADNE_INPUT:<input>:<attempt>] marker (a dispatched Ariadne owner input), when the owner mentions Ariadne, or when publishing findings, questions or results to Ariadne. Explains what Ariadne is and how to read items, publish replies and finish a claimed input with the installed ariadne CLI.";

/// Keep `only:<agent>` blocks for `agent`; drop the others. Marker lines vanish.
fn select(body: &str, agent: &str) -> Result<String, String> {
    let mut out = String::new();
    let mut block: Option<String> = None;
    for line in body.split_inclusive('\n') {
        let trimmed = line.trim();
        if let Some(name) = trimmed
            .strip_prefix("<!-- only:")
            .and_then(|rest| rest.strip_suffix(" -->"))
        {
            if block.is_some() {
                return Err("Nested skill blocks are not allowed".into());
            }
            block = Some(name.to_owned());
        } else if trimmed == "<!-- /only -->" {
            if block.take().is_none() {
                return Err("Unmatched skill block end".into());
            }
        } else if block.as_deref().is_none_or(|name| name == agent) {
            out.push_str(line);
        }
    }
    if block.is_some() {
        return Err("Unterminated skill block".into());
    }
    Ok(out)
}

fn skill(skill_body: &str, rules: &str, agent: &str) -> Result<String, String> {
    let selected = select(skill_body, agent)?;
    let header = "<!-- Generated by cargo xtask gen-rules from rules/skill.md. Do not edit. -->";
    Ok(if agent == "claude" {
        let reference = "the Ariadne setup instruction shown when the session was connected\n(installed as `rules/claude.md`)";
        format!(
            "---\nname: ariadne\ndescription: {CLAUDE_DESCRIPTION}\n---\n{header}\n{}",
            selected.replace("{{RULES}}", reference)
        )
    } else {
        let reference = "the Ariadne setup instruction the owner pasted into this thread and in the\nrules below";
        format!(
            "---\nname: ariadne\ndescription: {CODEX_DESCRIPTION}\n---\n{header}\n{}\n{rules}",
            selected.replace("{{RULES}}", reference)
        )
    })
}

fn write_or_check(target: &Path, content: &str, check: bool) -> Result<(), String> {
    if target.is_symlink() {
        return Err(format!("Rule output is symlinked: {}", target.display()));
    }
    if check {
        if fs::read_to_string(target).map_err(|error| format!("{}: {error}", target.display()))?
            != content
        {
            return Err(format!("Stale generated rules: {}", target.display()));
        }
        Ok(())
    } else {
        fs::write(target, content).map_err(|error| format!("{}: {error}", target.display()))
    }
}

fn read_source(path: &Path) -> Result<String, String> {
    if path.is_symlink() {
        return Err("Rule source must be a regular owned repository file".into());
    }
    let body = fs::read_to_string(path).map_err(|error| format!("{}: {error}", path.display()))?;
    if body.trim().is_empty() || body.contains('\0') {
        return Err("Rule source must be nonblank and NUL-free".into());
    }
    Ok(body)
}

pub fn generate(root: &Path, check: bool) -> Result<(), String> {
    let directory = root.join("integrations/rules");
    for path in [root.join("integrations"), directory.clone()] {
        if path.is_symlink() {
            return Err(format!("Rule path is symlinked: {}", path.display()));
        }
    }
    let body = read_source(&directory.join("source.md"))?;
    let skill_body = read_source(&directory.join("skill.md"))?;
    let content =
        format!("<!-- Generated by cargo xtask gen-rules from source.md. Do not edit. -->\n{body}");
    for name in ["claude.md", "codex.md"] {
        write_or_check(&directory.join(name), &content, check)?;
    }
    for (agent, relative) in [
        ("claude", "integrations/claude/plugin/skills/ariadne"),
        ("codex", "integrations/codex/skills/ariadne"),
    ] {
        let target_directory = root.join(relative);
        let mut ancestor = target_directory.as_path();
        while ancestor != root {
            if ancestor.is_symlink() {
                return Err(format!("Skill path is symlinked: {}", ancestor.display()));
            }
            ancestor = ancestor.parent().ok_or("Skill path escapes the root")?;
        }
        if !check {
            fs::create_dir_all(&target_directory)
                .map_err(|error| format!("{}: {error}", target_directory.display()))?;
        }
        write_or_check(
            &target_directory.join("SKILL.md"),
            &skill(&skill_body, &body, agent)?,
            check,
        )?;
    }
    Ok(())
}
