//! Deterministic adapter instructions from one authored shared rule source.
use std::{fs, path::Path};

pub fn generate(root: &Path, check: bool) -> Result<(), String> {
    let directory = root.join("integrations/rules");
    for path in [root.join("integrations"), directory.clone()] {
        if path.is_symlink() {
            return Err(format!("Rule path is symlinked: {}", path.display()));
        }
    }
    let source = directory.join("source.md");
    if source.is_symlink() {
        return Err("Rule source must be a regular owned repository file".into());
    }
    let body =
        fs::read_to_string(&source).map_err(|error| format!("{}: {error}", source.display()))?;
    if body.trim().is_empty() || body.contains('\0') {
        return Err("Rule source must be nonblank and NUL-free".into());
    }
    let content =
        format!("<!-- Generated by cargo xtask gen-rules from source.md. Do not edit. -->\n{body}");
    for name in ["claude.md", "codex.md"] {
        let target = directory.join(name);
        if target.is_symlink() {
            return Err(format!("Rule output is symlinked: {}", target.display()));
        }
        if check {
            if fs::read_to_string(&target)
                .map_err(|error| format!("{}: {error}", target.display()))?
                != content
            {
                return Err(format!("Stale generated rules: {}", target.display()));
            }
        } else {
            fs::write(&target, &content)
                .map_err(|error| format!("{}: {error}", target.display()))?;
        }
    }
    Ok(())
}
