[package]
name = "ariadne-domain"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
schemars.workspace = true
ts-rs = { workspace = true, features = ["serde-json-impl", "no-serde-warnings"] }
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true

[dev-dependencies]
jsonschema.workspace = true
