use std::{fs, os::unix::fs::symlink, path::Path};

const ON_DEMAND: [&str; 7] = [
    "inputs.md",
    "errors.md",
    "reconnect.md",
    "report.md",
    "review.md",
    "checklist.md",
    "follow-up.md",
];
const SKILL: &str = "Shared body.\n<!-- only:claude -->\nClaude only.\n<!-- /only -->\n<!-- only:codex -->\nCodex only.\n<!-- /only -->\nSee {{RULES}}.\n";
const PATTERNS: &str = "Shared patterns.\n<!-- only:claude -->\nClaude example.\n<!-- /only -->\n<!-- only:codex -->\nCodex example.\n<!-- /only -->\n";

fn sources(rules: &Path, source: &str) {
    fs::create_dir_all(rules).unwrap();
    fs::write(rules.join("source.md"), source).unwrap();
    fs::write(rules.join("skill.md"), SKILL).unwrap();
    for name in ON_DEMAND {
        fs::write(rules.join(name), PATTERNS).unwrap();
    }
}

#[test]
fn one_source_generates_adapter_guidance_and_detects_stale_outputs() {
    let root = tempfile::tempdir().unwrap();
    let rules = root.path().join("integrations/rules");
    sources(
        &rules,
        "Full exact reply.\nRetain original operation IDs.\n",
    );
    ariadne_xtask::rules::generate(root.path(), false).unwrap();
    // The rule sheets are the skill text for each agent, without front matter.
    let claude = fs::read_to_string(rules.join("claude.md")).unwrap();
    let codex = fs::read_to_string(rules.join("codex.md")).unwrap();
    assert!(claude.contains("Claude only.") && !claude.contains("Codex only."));
    assert!(codex.contains("Codex only.") && !codex.contains("Claude only."));
    assert!(claude.contains("Retain original operation IDs.") && !claude.starts_with("---"));
    ariadne_xtask::rules::generate(root.path(), true).unwrap();
    fs::write(rules.join("source.md"), "Changed canonical guidance.\n").unwrap();
    assert!(ariadne_xtask::rules::generate(root.path(), true)
        .unwrap_err()
        .contains("Stale"));
    ariadne_xtask::rules::generate(root.path(), false).unwrap();
    ariadne_xtask::rules::generate(root.path(), true).unwrap();
}

#[test]
fn one_skill_source_generates_agent_specific_skills_and_detects_stale_outputs() {
    let root = tempfile::tempdir().unwrap();
    let rules = root.path().join("integrations/rules");
    sources(&rules, "Full exact reply.\n");
    ariadne_xtask::rules::generate(root.path(), false).unwrap();
    // Every on-demand file ships beside both skills, filtered per agent.
    for (agent, directory, other) in [
        ("Claude", "claude/plugin/skills/ariadne", "Codex"),
        ("Codex", "codex/skills/ariadne", "Claude"),
    ] {
        for name in ON_DEMAND {
            let path = root.path().join("integrations").join(directory).join(name);
            let text = fs::read_to_string(&path).unwrap();
            assert!(text.starts_with(&format!(
                "<!-- Generated by cargo xtask gen-rules from rules/{name}."
            )));
            assert!(
                text.contains("Shared patterns.") && text.contains(&format!("{agent} example."))
            );
            assert!(!text.contains(&format!("{other} example.")) && !text.contains("<!-- only:"));
            fs::write(&path, "edited").unwrap();
            assert!(ariadne_xtask::rules::generate(root.path(), true)
                .unwrap_err()
                .contains("Stale"));
            ariadne_xtask::rules::generate(root.path(), false).unwrap();
        }
        assert!(!root
            .path()
            .join("integrations")
            .join(directory)
            .join("playbook.md")
            .exists());
    }
    fs::remove_file(rules.join("follow-up.md")).unwrap();
    assert!(ariadne_xtask::rules::generate(root.path(), true).is_err());
    fs::write(rules.join("follow-up.md"), PATTERNS).unwrap();
    let claude = fs::read_to_string(
        root.path()
            .join("integrations/claude/plugin/skills/ariadne/SKILL.md"),
    )
    .unwrap();
    let codex_path = root
        .path()
        .join("integrations/codex/skills/ariadne/SKILL.md");
    let codex = fs::read_to_string(&codex_path).unwrap();
    assert!(claude.starts_with("---\nname: ariadne\ndescription: "));
    assert!(codex.starts_with("---\nname: ariadne\ndescription: "));
    // The description is short and routes a dispatched input.
    for text in [&claude, &codex] {
        let description = text.lines().nth(2).unwrap();
        assert!(description.contains("[ARIADNE_INPUT:"));
        assert!(
            description.len() <= "description: ".len() + 200,
            "{description}"
        );
    }
    assert!(claude.lines().nth(2).unwrap().contains("/ariadne-connect"));
    assert!(claude.contains("Claude only.") && !claude.contains("Codex only."));
    assert!(codex.contains("Codex only.") && !codex.contains("Claude only."));
    assert!(codex.ends_with("Full exact reply.\n"));
    assert!(!claude.contains("{{") && !codex.contains("{{"));
    ariadne_xtask::rules::generate(root.path(), true).unwrap();
    fs::write(&codex_path, "edited").unwrap();
    assert!(ariadne_xtask::rules::generate(root.path(), true)
        .unwrap_err()
        .contains("Stale"));
    fs::write(rules.join("skill.md"), "<!-- only:codex -->\nopen\n").unwrap();
    assert!(ariadne_xtask::rules::generate(root.path(), false)
        .unwrap_err()
        .contains("Unterminated"));
}

#[test]
fn symlinked_rule_target_is_rejected_without_overwriting_unrelated_content() {
    let root = tempfile::tempdir().unwrap();
    let rules = root.path().join("integrations/rules");
    sources(&rules, "Valid full reply guidance.\n");
    let other = root.path().join("unrelated.md");
    fs::write(&other, "Keep this owner's file.").unwrap();
    symlink(&other, rules.join("claude.md")).unwrap();
    assert!(ariadne_xtask::rules::generate(root.path(), false).is_err());
    assert_eq!(
        fs::read_to_string(other).unwrap(),
        "Keep this owner's file."
    );
}
