import type { ReactNode } from 'react';
import { AnswerControl, type AnswerControlProps } from './AnswerControl';
import '../../styles/reference.css';

export type DeliveryLabel = { text: string; icon: string; color: string; action?: string; onAction?: () => void };
export type WaitingCard = { id: string; question: string; path: string; ask?: string; earlier?: string; previousRound?: string; age: string; messageTag: string; ring: string; answer: AnswerControlProps; delivery?: DeliveryLabel; onOpen?: () => void };
export type ReadOnlyWaitingCard = Omit<WaitingCard, 'answer'>;
export type SentCard = { id: string; question: string; delivery: DeliveryLabel; detail?: ReactNode; onOpen?: () => void };
export type GlobalWaitingPanelProps = { count: string; loading?: boolean; emptyText: string; emptyHeading?: string; emptyIcon?: string; notice?: ReactNode; sentCaption?: string; waiting: readonly WaitingCard[]; readOnlyWaiting?: readonly ReadOnlyWaitingCard[]; sent: readonly SentCard[] };
export function GlobalWaitingPanel({ count, loading, emptyText, emptyHeading = 'Nothing waiting on you', emptyIcon = 'ph ph-check-circle', notice, sentCaption = 'waiting for the agent to pick up', waiting, readOnlyWaiting = [], sent }: GlobalWaitingPanelProps) {
  const cards: readonly (ReadOnlyWaitingCard & { answer?: AnswerControlProps })[] = [...waiting, ...readOnlyWaiting];
  return <aside className="ariadne-reference ref-waiting" aria-label="Waiting on me"><div className="ref-waiting-heading"><span>Waiting on me</span><span className="ref-waiting-count">{count}</span><span>Oldest first</span></div><div className="ref-waiting-scroll">
    {notice}
    {loading ? [1, 2].map(id => <div className="ref-waiting-skeleton" key={id} aria-label="Loading waiting questions"><span /><span /><span /><span /></div>) : cards.length === 0 && <div className="ref-waiting-empty"><i className={emptyIcon} aria-hidden="true" /><div>{emptyHeading}</div><p>{emptyText}</p></div>}
    {cards.map(card => <div key={card.id} className="ref-waiting-card" style={{ boxShadow: card.ring }}><div className="ref-waiting-path">{card.path}</div><div className="ref-waiting-question">{card.question}</div>{card.ask && <div className="ref-waiting-ask">{card.ask}</div>}{card.earlier && <div className="ref-waiting-context"><i className="ph ph-clock-counter-clockwise" aria-hidden="true" /><span>{card.earlier}</span></div>}{card.previousRound && <div className="ref-waiting-context"><i className="ph ph-arrows-clockwise" aria-hidden="true" /><span>{card.previousRound}</span></div>}{card.delivery && <div className="ref-delivery" style={{ color: card.delivery.color }}><i className={card.delivery.icon} aria-hidden="true" /><span>{card.delivery.text}</span>{card.delivery.action && <button type="button" className="ref-button ref-secondary" onClick={card.delivery.onAction}>{card.delivery.action}</button>}</div>}{card.answer && <AnswerControl {...card.answer} />}<div className="ref-waiting-age"><i className="ph ph-clock" aria-hidden="true" /><span>Waiting {card.age} · asked in {card.messageTag}</span><button type="button" className="ref-button ref-ghost" onClick={card.onOpen}>Details</button></div></div>)}
    {sent.length > 0 && <><div className="ref-sent-label">Sent<span>· {sentCaption}</span></div>{sent.map(input => <div key={input.id} className="ref-sent-card" role="button" tabIndex={0} onClick={input.onOpen} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); input.onOpen?.(); } }}><div>{input.question}</div><div style={{ color: input.delivery.color }}><i className={input.delivery.icon} aria-hidden="true" /><span>{input.delivery.text}</span></div>{input.detail}</div>)}</>}
  </div></aside>;
}
