import '../../styles/reference.css';

export type ProjectCardProps = { name: string; path: string; sessionsText: string; runText: string; runColor: string; runDot: string; runRing: string; waitText: string; waitColor: string; last: string; agents: readonly string[]; ring: string; candidate?: boolean; incomplete?: boolean; disabled?: boolean; onOpen?: () => void };
export function ProjectCard({ name, path, sessionsText, runText, runColor, runDot, runRing, waitText, waitColor, last, agents, ring, candidate, incomplete, disabled, onOpen }: ProjectCardProps) {
  return <div className="ariadne-reference ref-project-card" role="button" aria-disabled={disabled || undefined} tabIndex={disabled ? -1 : 0} onClick={disabled ? undefined : onOpen} onKeyDown={event => { if (!disabled && (event.key === 'Enter' || event.key === ' ')) { event.preventDefault(); onOpen?.(); } }} style={{ boxShadow: ring }}>
    <div className="ref-project-heading"><i className="ph ph-folder-simple" aria-hidden="true" /><div><span>{name}</span><span className="ref-project-path">{path}</span></div></div>
    <div className="ref-project-stats"><span><i className="ph ph-chats-teardrop" aria-hidden="true" />{sessionsText}</span><span style={{ color: runColor }}><span className="ref-run-dot" style={{ background: runDot, boxShadow: runRing }} />{candidate ? 'Candidate · not bound' : runText}</span><span style={{ color: waitColor }}><i className="ph-fill ph-question" aria-hidden="true" />{incomplete ? `${waitText} · incomplete` : waitText}</span><span><i className="ph ph-clock" aria-hidden="true" />{last}</span></div>
    <div className="ref-project-agents">{agents.map(agent => <span className="ref-agent-tag" key={agent}><i className="ph ph-terminal-window" aria-hidden="true" />{agent}</span>)}</div>
  </div>;
}
export type SessionCardProps = { title: string; meta: string; titleColor: string; background: string; run: string; runColor: string; runDot: string; runRing: string; actions: readonly { label: string; icon: string; kind: 'primary' | 'secondary' | 'ghost'; disabled?: boolean; onClick?: () => void }[]; topics: readonly { name: string; counts: string; icon: string; color: string }[] };
export function SessionCard({ title, meta, titleColor, background, run, runColor, runDot, runRing, actions, topics }: SessionCardProps) {
  return <div className="ariadne-reference ref-session-card" style={{ background }}><div className="ref-session-heading"><i className="ph ph-terminal-window" aria-hidden="true" style={{ fontSize: 18, color: 'color-mix(in srgb, var(--color-text) 70%, transparent)' }} /><div className="ref-session-identity"><span style={{ fontSize: 14, fontWeight: 500, color: titleColor }}>{title}</span><span style={{ fontSize: 12.5, color: 'color-mix(in srgb, var(--color-text) 62%, transparent)' }}>{meta}</span></div><span className="ref-session-running" style={{ color: runColor }}><span className="ref-run-dot" style={{ width: 7, height: 7, background: runDot, boxShadow: runRing }} />{run}</span><span style={{ display: 'flex', gap: 6 }}>{actions.map(action => <button key={action.label} type="button" className={`ref-button ref-${action.kind}`} disabled={action.disabled} style={{ height: 30, fontSize: 13 }} onClick={action.onClick}><i className={action.icon} aria-hidden="true" style={{ fontSize: 13 }} />{action.label}</button>)}</span></div>{topics.length > 0 && <div className="ref-session-topics">{topics.map(topic => <span key={topic.name} style={{ color: topic.color }}><i className={topic.icon} aria-hidden="true" />{topic.name}<span>{topic.counts}</span></span>)}</div>}</div>;
}
