import type { ReactNode } from 'react';
import { GlobalWaitingPanel, type GlobalWaitingPanelProps } from './GlobalWaitingPanel';
import { MessageExcerpt, type MessageExcerptProps } from './MessageExcerpt';
import '../../styles/reference.css';

export type ReferenceWorkspaceProps = {
  header: { session: string; binding: string; bindingColor: string; bindingGlow: string; demo?: boolean; query: string; views: readonly { label: string; icon: string; title: string; background: string; color: string }[]; railColor: string; themeIcon: string; themeTitle: string };
  tabs: readonly { id?: string; title: string; label: string; project?: string; sub: string; icon: string; iconSize: string; iconColor: string; color: string; background: string; bar: string; closable: boolean; selected?: boolean; disabled?: boolean; onSelect?: () => void; onClose?: () => void }[];
  waiting: GlobalWaitingPanelProps; center: ReactNode; detail?: ReactNode;
  rail?: { messages: readonly MessageExcerptProps[]; count: string; emptyText: string; followText: string; followIcon: string; followColor: string; newText?: string };
  summary: string; overlay?: ReactNode; onCloseDetail?: () => void; onCloseRail?: () => void; onJumpLatest?: () => void;
};
export function ReferenceWorkspace({ header, tabs, waiting, center, detail, rail, summary, overlay, onCloseDetail, onCloseRail, onJumpLatest }: ReferenceWorkspaceProps) {
  return <div className="ariadne-reference ref-workspace">
    <header className="ref-header"><div className="ref-brand"><i className="ph ph-spiral" aria-hidden="true" /><span>Ariadne</span></div><div className="ref-header-context">{header.demo && <span className="ref-tag ref-tag-accent">Demo</span>}<span>{header.session}</span><span><span className="ref-run-dot" style={{ width: 7, height: 7, background: header.bindingColor, boxShadow: header.bindingGlow }} /><span>{header.binding}</span></span></div><div style={{ flex: 1 }} /><label className="ref-search"><i className="ph ph-magnifying-glass" aria-hidden="true" /><input className="ref-input" aria-label="Search questions and outcomes" value={header.query} readOnly placeholder="Search questions and outcomes" /><span>/</span></label>{header.views.length > 0 && <div className="ref-view-tabs">{header.views.map(view => <button type="button" key={view.label} title={view.title} style={{ background: view.background, color: view.color }}><i className={view.icon} aria-hidden="true" />{view.label}</button>)}</div>}<button type="button" className="ref-button ref-secondary ref-chrome-icon" title="Messages (m)" style={{ color: header.railColor }} onClick={onCloseRail}><i className="ph ph-chats-teardrop" aria-hidden="true" /></button><button type="button" className="ref-button ref-secondary ref-chrome-icon" title={header.themeTitle}><i className={header.themeIcon} aria-hidden="true" /></button></header>
    <nav className="ref-tabs" aria-label="Projects and sessions">{tabs.map((tab, index) => <div key={tab.id ?? index} style={{ background: tab.background }}><button type="button" title={tab.title} disabled={tab.disabled} aria-current={tab.selected ? 'page' : undefined} onClick={tab.onSelect} style={{ paddingRight: tab.closable ? 2 : 12, color: tab.color }}><i className={tab.icon} aria-hidden="true" style={{ fontSize: tab.iconSize, color: tab.iconColor }} />{tab.project && <><span className="ref-tab-project">{tab.project}</span><span className="ref-tab-separator">/</span></>}<span style={{ fontWeight: 500 }}>{tab.label}</span><span className="ref-tab-sub">{tab.sub}</span></button>{tab.closable && <button type="button" className="ref-tab-close" disabled={tab.disabled} onClick={tab.onClose} title="Close tab (the session stays as it is)" aria-label={tab.onClose ? `Close ${tab.label} tab` : 'Close tab'}><i className="ph ph-x" aria-hidden="true" /></button>}<span className="ref-tab-bar" style={{ background: tab.bar }} /></div>)}</nav>
    <div className="ref-workspace-body"><GlobalWaitingPanel {...waiting} /><div className="ref-workspace-scroll"><div className="ref-workspace-panels" style={{ minWidth: 560 + (detail ? 400 : 0) + (rail ? 240 : 0), gridTemplateColumns: `minmax(560px, 1fr)${detail ? ' 400px' : ''}${rail ? ' 240px' : ''}` }}><main className="ref-center">{center}</main>{detail && <aside className="ref-detail" aria-label="Item detail"><button type="button" className="ref-detail-close ref-button ref-ghost" aria-label="Close detail" onClick={onCloseDetail}><i className="ph ph-x" aria-hidden="true" /></button><div className="ref-detail-scroll">{detail}</div></aside>}{rail && <aside className="ref-rail" aria-label="Messages"><div className="ref-rail-heading"><span>Messages</span><span>{rail.count}</span><button type="button" className="ref-button ref-ghost" title="Follow new messages" style={{ color: rail.followColor }} onClick={onJumpLatest}><i className={rail.followIcon} aria-hidden="true" />{rail.followText}</button><button type="button" className="ref-button ref-ghost" title="Hide messages (m)" onClick={onCloseRail}><i className="ph ph-x" aria-hidden="true" /></button></div><div className="ref-rail-scroll">{rail.messages.length === 0 && <div className="ref-rail-empty">{rail.emptyText}</div>}{rail.messages.map((message, index) => <MessageExcerpt {...message} key={index} />)}</div>{rail.newText && <button type="button" className="ref-button ref-secondary ref-jump" onClick={onJumpLatest}><i className="ph ph-arrow-down" aria-hidden="true" />{rail.newText}</button>}</aside>}</div></div></div>
    <footer className="ref-footer"><span className="ref-keycap">↑↓</span>move<span className="ref-keycap">←→</span>fold<span className="ref-keycap">a</span>answer<span className="ref-keycap">1–9</span>choose<span className="ref-keycap">⌘↵</span>send<span className="ref-keycap">↵</span>details<span className="ref-keycap">/</span>search<span className="ref-keycap">g</span>graph<span className="ref-keycap">m</span>messages<span className="ref-footer-summary">{summary}</span></footer>{overlay}
  </div>;
}
