import { useState } from 'react';
import fixtures from './workspace-fixtures.json';
import { ReferenceWorkspace, type ReferenceWorkspaceProps } from '../../../apps/desktop/src/components/reference/ReferenceWorkspace';
import { BackAndForthRound, type BackAndForthRoundProps } from '../../../apps/desktop/src/components/reference/BackAndForthRound';
import { TopicGraph, type TopicGraphProps } from '../../../apps/desktop/src/components/reference/TopicGraph';
import { ProjectCard, SessionCard, type ProjectCardProps, type SessionCardProps } from '../../../apps/desktop/src/components/reference/ProjectSessionCard';
import { ArchiveCard, ContinueTopic, GuardDialog, type ArchiveCardProps, type ContinueTopicProps } from '../../../apps/desktop/src/components/reference/ReferenceDialog';
import { TreeRow, type TreeRowProps } from '../../../apps/desktop/src/components/reference/TreeRow';
import { AnswerControl, type AnswerControlProps } from '../../../apps/desktop/src/components/reference/AnswerControl';
import { StatusBadge, type Status } from '../../../apps/desktop/src/components/reference/StatusBadge';
import { MessageExcerpt, type MessageExcerptProps } from '../../../apps/desktop/src/components/reference/MessageExcerpt';

export type GalleryFrame = Pick<ReferenceWorkspaceProps, 'header' | 'tabs' | 'waiting' | 'summary' | 'rail'> & {
  rows: readonly { topic?: { name: string; counts: readonly { icon: string; color: string; text: string }[]; expanded: boolean; padTop: string; background: string; ring: string; nameColor: string; session?: string; prompt?: string }; item?: TreeRowProps; answering?: boolean }[];
  detail?: { id: string; question: string; status: Status; meta: string; path: readonly string[]; outcome?: string; why?: string; note?: string; rounds: readonly BackAndForthRoundProps[]; timeline: readonly MessageExcerptProps[]; options: AnswerControlProps['options']; draft: string; reply: boolean; replyTitle: string; actions: readonly { label: string; icon: string; kind: string; key: string; title: string; disabled: boolean }[]; delivery?: { icon: string; text: string; color: string }; children: readonly { id: string; question: string; status: Status }[]; replacement?: { question: string; status: Status }; reopen?: string };
  graphs: readonly { name: string; counts: string; session?: string; graph: TopicGraphProps }[];
  projects: readonly ProjectCardProps[]; projectSubtitle: string;
  sessionGroups: readonly { name: string; path: string; activeLabel: string; closedLabel: string; active: readonly SessionCardProps[]; closed: readonly SessionCardProps[] }[];
  sessionSubtitle: string; archive?: readonly ArchiveCardProps[];
  continuation?: { title: string; groups: ContinueTopicProps['groups'] };
  empty: boolean; loading: boolean; first: boolean; noMatch?: string; reveal: boolean;
  filters?: { chips: readonly { label: string; icon: string; iconColor: string; count: number; background: string; color: string; ring: string }[]; topic: string; topics: readonly { id: string; name: string }[] };
  sessionBar?: { title: string; meta: string; run: string; runColor: string; runDot: string; runRing: string };
};
// Immutable source-derived presentation values, not a second domain/read model.
// The JSON contains no source compiler, React 18 runtime, timers or workflows.
export const workspaceFixtures = Object.fromEntries(Object.entries(fixtures.frames).map(([id, fields]) => [id, Object.fromEntries(Object.entries(fields).map(([field, index]) => [field, fixtures.fragments[index]]))])) as unknown as Record<string, GalleryFrame>;
const noop = () => {};
const heading = (text: string) => <div className="ref-section-label">{text}</div>;
function ControlledAnswer(props: Omit<AnswerControlProps, 'onSelect' | 'onDraft' | 'onSubmit'>) {
  const [selected, select] = useState(props.selected ?? null), [draft, edit] = useState(props.draft);
  return <AnswerControl {...props} selected={selected} draft={draft} onSelect={select} onDraft={edit} onSubmit={noop} />;
}
function FrameDetail({ detail }: { detail: NonNullable<GalleryFrame['detail']> }) {
  return <><div className="ref-detail-path">{detail.path.join(' › ')}</div><section className="ref-detail-question"><StatusBadge status={detail.status} /><h2>{detail.question}</h2><span>{detail.meta}</span></section>{detail.actions.length > 0 && <section className="ref-detail-actions">{detail.actions.filter(action => detail.status !== 'replaced' || action.key !== 'o').map(action => <button type="button" className={`ref-button ref-${action.kind}`} title={action.title} disabled={action.disabled} key={action.key}><i className={action.icon} aria-hidden="true" />{action.key === 'o' ? 'Request reopen' : action.label}<span className="ref-keycap">{action.key}</span></button>)}</section>}{detail.delivery && <div className="ref-delivery" style={{ color: detail.delivery.color }}><i className={detail.delivery.icon} aria-hidden="true" /><span>{detail.delivery.text}</span></div>}{detail.options.length > 0 && <section>{heading('Your answer')}<ControlledAnswer options={detail.options} selected={null} draft={detail.draft} /></section>}{detail.reply && <section>{heading(detail.replyTitle || 'Reply')}<ControlledAnswer options={[]} selected={null} draft={detail.draft} /></section>}{detail.outcome && <section>{heading('Outcome')}<p>{detail.outcome}</p></section>}{detail.why && <section>{heading('Why')}<p>{detail.why}</p></section>}{detail.note && <section>{heading('Agent note')}<p>{detail.note}</p></section>}{detail.reopen && <section>{heading('Before reopening')}<p>{detail.reopen}</p></section>}{detail.replacement && <section>{heading('Replaced by')}<StatusBadge status={detail.replacement.status} /><p>{detail.replacement.question}</p></section>}{detail.children.length > 0 && <section>{heading(`Branched into ${detail.children.length} items`)}{detail.children.map(child => <div key={child.id} className="ref-detail-child"><StatusBadge status={child.status} variant="icon" size={15} /><span>{child.question}</span></div>)}</section>}{detail.rounds.length > 0 && <section className="ref-rounds">{heading('Back and forth')}{detail.rounds.map(round => <BackAndForthRound {...round} key={round.label} />)}</section>}<section>{heading('Timeline')}{detail.timeline.map((message, index) => <MessageExcerpt {...message} key={index} />)}</section><code>{detail.id}</code></>;
}
export function WorkspaceCase({ frameId, variant }: { frameId: string; variant?: string }) {
  const frame = workspaceFixtures[frameId];
  if (!frame) throw new Error(`Unknown assembled fixture ${frameId}`);
  const [detailOpen, setDetailOpen] = useState(!!frame.detail), [railOpen, setRailOpen] = useState(!!frame.rail), [overlayOpen, setOverlayOpen] = useState(!!frame.continuation || !!variant), [dispatch, setDispatch] = useState<'enabled' | 'pausing' | 'paused'>('enabled');
  const close = () => setOverlayOpen(false);
  const waiting = { ...frame.waiting, waiting: frame.waiting.waiting.map(card => ({ ...card, answer: { ...card.answer, onSelect: noop, onDraft: noop, onSubmit: noop } })) };
  const center = <>
    {frame.sessionBar && <div className="ref-session-bar"><i className="ph ph-terminal-window" aria-hidden="true" /><strong>{frame.sessionBar.title}</strong><span>{frame.sessionBar.meta}</span><span style={{ color: frame.sessionBar.runColor }}>{frame.sessionBar.run}</span></div>}
    {frame.filters && <div className="ref-filters">{frame.filters.chips.map(chip => <button type="button" key={chip.label} style={{ background: chip.background, color: chip.color, boxShadow: chip.ring }}><i className={chip.icon} aria-hidden="true" style={{ color: chip.iconColor }} /><span>{chip.label}</span><span>{chip.count}</span></button>)}<select aria-label="Topic" value={frame.filters.topic} onChange={noop}><option value="all">All topics</option>{frame.filters.topics.map(topic => <option value={topic.id} key={topic.id}>{topic.name}</option>)}</select></div>}
    {frame.reveal && <div className="ref-reveal">Revealed outside the current filters · saved filters are retained</div>}
    {frame.projects.length > 0 && <div className="ref-page"><div className="ref-page-heading">Projects<span>{frame.projectSubtitle}</span></div><div className="ref-project-grid">{frame.projects.map(project => <ProjectCard {...project} key={project.path} />)}</div></div>}
    {frame.sessionGroups.length > 0 && <div className="ref-page"><div className="ref-page-heading">{frameId === '1z' ? 'All sessions' : 'Project'}<span>{frame.sessionSubtitle}</span></div>{frame.sessionGroups.map(group => <section className="ref-session-group" key={group.path}><div className="ref-page-heading">{group.name}</div><div className="ref-project-path">{group.path}</div>{group.active.length > 0 && <>{heading(group.activeLabel)}{group.active.map(session => <SessionCard {...session} key={session.meta} />)}</>}{group.closed.length > 0 && <>{heading(group.closedLabel)}{group.closed.map(session => <SessionCard {...session} key={session.meta} />)}</>}</section>)}</div>}
    {frame.archive && <div className="ref-page"><div className="ref-page-heading">Archive</div>{frame.archive.map(topic => <ArchiveCard {...topic} key={topic.name} />)}</div>}
    {frame.graphs.length > 0 && <div className="ref-graphs">{frame.graphs.map(graph => <section key={graph.name}><div className="ref-graph-heading"><span>{graph.name}</span><span>{graph.session}</span><span>{graph.counts}</span></div><TopicGraph {...graph.graph} /></section>)}</div>}
    {frame.loading && <div className="ref-page" aria-label="Loading session">Loading session…{[1, 2, 3, 4].map(id => <div className="ref-waiting-skeleton" key={id}><span /><span /></div>)}</div>}
    {frame.empty && <div className="ref-page"><h2>A new session</h2><p>Questions and decisions appear here when the agent publishes them.</p></div>}
    {frame.first && <div className="ref-page"><h2>Connect an existing session</h2><p>Discovered candidates are read-only. Register the project and explicitly bind the session before sending.</p><ProjectCard name="payments-sdk" path="~/Documents/Code/payments-sdk" sessionsText="Discovered candidate" runText="Not bound" runColor="var(--st-open)" runDot="transparent" runRing="none" waitText="Unknown" waitColor="var(--st-open)" last="Not registered" agents={['claude-code']} ring="0 0 0 1px var(--color-divider)" candidate /></div>}
    {frame.noMatch && <div className="ref-page">{frame.noMatch}</div>}
    {frame.rows.length > 0 && <div role="tree" className="ref-tree">{frame.rows.map((row, index) => row.topic ? <div key={index} className="ref-topic" style={{ paddingTop: row.topic.padTop, background: row.topic.background, boxShadow: row.topic.ring }}><div><i className={`ph ph-caret-${row.topic.expanded ? 'down' : 'right'}`} aria-hidden="true" /><span style={{ color: row.topic.nameColor }}>{row.topic.name}</span></div><div className="ref-topic-counts">{row.topic.counts.map(count => <span key={count.text} style={{ color: count.color }}><i className={count.icon} aria-hidden="true" />{count.text}</span>)}</div>{row.topic.session && <span>{row.topic.session}</span>}{row.topic.prompt && <span>{row.topic.prompt}</span>}</div> : row.item ? <TreeRow {...row.item} key={row.item.item.id} answer={row.answering ? <ControlledAnswer options={waiting.waiting.find(card => card.id === row.item?.item.id)?.answer.options ?? []} selected={null} draft="" noText /> : undefined} /> : null)}</div>}
  </>;
  const overlay = overlayOpen && (variant === 'archive-blocked' || variant === 'archive-eligible' || variant === 'close-guard' ? <GuardDialog kind={variant === 'close-guard' ? 'close' : 'archive'} title={variant === 'close-guard' ? 'Close session' : 'Archive topic'} blockers={variant === 'archive-blocked' ? [{ id: 'item-4.1', label: 'Waiting on you' }, { id: 'input-2', label: 'Delivery uncertain' }] : []} dispatch={dispatch} onReveal={noop} onPause={() => setDispatch('pausing')} onConfirm={close} onCancel={close} /> : frame.continuation ? <ContinueTopic title={frame.continuation.title} source="codex · yesterday" target="claude-code · today" groups={frame.continuation.groups} error={variant === 'target-error' ? 'Target write failed' : undefined} onCancel={close} onSend={close} /> : undefined);
  return <ReferenceWorkspace header={{ ...frame.header, themeIcon: document.documentElement.dataset.theme === 'light' ? 'ph ph-moon' : 'ph ph-sun', themeTitle: document.documentElement.dataset.theme === 'light' ? 'Switch to dark' : 'Switch to light' }} tabs={frame.tabs} waiting={waiting} summary={frame.summary} center={center} detail={detailOpen && frame.detail ? <FrameDetail detail={variant === 'ask-only' ? { ...frame.detail, rounds: [{ ...frame.detail.rounds[2], isNow: false }] } : frame.detail} /> : undefined} rail={railOpen ? variant === 'paused-follow' && frame.rail ? { ...frame.rail, followText: 'Follow latest', followIcon: 'ph ph-arrow-down', newText: '3 new messages · Jump to latest' } : frame.rail : undefined} overlay={overlay} onCloseDetail={() => setDetailOpen(false)} onCloseRail={() => setRailOpen(value => !value)} />;
}
